### ISSUE TITLE
Epic: Subsystem 2- Simulation

### ISSUE THREAD

**Issue by IssaNseir** [Superhoben/MD-simulation-CDIO#12]
**Obs: (1) is priority 1 and (2) is priority 2, (reformulate)**

- [x]  read an arbitrary configuration of atom coordinates and velocities from the config. file (1)
- [x]  make an arbitrary configuration of atom coordinates and velocities from the config. file (1)
- [x]  read lattice constants, basis vectors and lattice vectors (reformulate)
- [x]  handle periodic boundary conditions (1)
- [x] utilize two-body interatomic potential functions dependant on the distance between atoms (1)
- [x] use routines to calculate temperature and pressure (1)
- [x] support constant temperature simulations (1)
- [x] calculate bulk properties: lattice constant, bulk modulus and  (1)
- [x] calculate cohesive energy (1)
- [x] calculate time-averages of the mean square displacement, the Debye temperature, the Lindemann criterion, the self diffusion coefficient and the specific heat of the materia (1)
- [x] the simulation should be carried out using somewhat physically relevant interatomic potential for the material (1)
- [x] produce a reasonable lattice constant (reformulate)

- [ ]  add random disturbances to any initial condition (2)
- [x] utilize many-body interatomic potential functions (2)
- [ ] update the atom coordinates according to methods at least second order accurate in time (2)
- [ ] take stability into account when choosing the time step for updating the state (2)
- [x] total energy should remain approximately constant (2)
- [x] at least a hundred atoms over a 10 picosecond time frame should finish in less than 2 hours on a personal compute (2)
- [x] keep the total energy of the system constant unless any external energy source is specified (2)
- [ ] perform 2-dimensional simulations (2)
- [x] routines for other material properties such as elastic moduli and elastic constants (2)
