### ISSUE TITLE
Epic: Testing

### ISSUE THREAD

**Issue by emelie042** [Superhoben/MD-simulation-CDIO#13]
- [x] Make sure simulations reproduce a reasonable lattice constant (reformulate)
- [x] Make sure simulations reproduce reasonable results for all implemented properties (1)
- [ ] Carry out unit tests on all the software (2)

When testing if simulations reproduce reasonable properties they must:
- [x] Reach equilibrium (1)
- [x] Have an optimized (close to zero) internal pressure (1)
