### ISSUE TITLE
Epic: Visualize the results

### ISSUE THREAD

**Issue by Superhoben** [Superhoben/MD-simulation-CDIO#2]
Owner: Jakov
Co-owner : Markus
- [x]  Read simulation data from file
- [x]  Create and save graphs (or other relevant visualization tool)
- [x]  Implement display function in GUI (?)
- [x]  Display graphs
