### ISSUE TITLE
Epic: The user is able to start MD-simulations and have the results presented through the user interface or an external visualization window

### ISSUE THREAD

**Issue by IssaNseir** [Superhoben/MD-simulation-CDIO#6]
- [x] Make an empty user interface (1)
- [x] Add a button to the user interface that starts a simulation (1)
- [x] Add a way to specify an interaction potential definition and parametrization through the user interface (1)
- [x] Show the results in the user interface (1)
- [x] Animation is still in progress (1)
- [x] Add a way to choose a configuration file through the user interface (2)
- [x] Add a way to create a configuration file through the user interface (2)
- [x] Show approximately how much is left of the simulation through the user interface (2)
- [x] Make the user interface user friendly (2)
