### ISSUE TITLE
Epic: The user is able to select through the user interface what material to simulate, for how long, and with which potential function to use

### ISSUE THREAD

**Issue by IssaNseir** [Superhoben/MD-simulation-CDIO#9]
- [x] Create a way to choose which material to simulate through the user interface (2)
- [x] Create a way to choose for how long to simulate something through the user interface (2)
- [x] Create a way to choose which potential function to use through the user interface (1)
